### ISSUE TITLE
Add text of license file

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/open-source-funders#3]
MIT.

**Comment by RichardLitt** [comment]
Possibly GPL? @wooorm Got a problem with GPL?

**Comment by wooorm** [comment]
Not necessarily a problem, but there are different facets of this: website, data, package(s) releasing that data to npm; are they all GPL?

**Comment by RichardLitt** [comment]
A different question: does any of that belong in a closed-source chain? I figure no, and that they could all be open source. :)

**Comment by wooorm** [comment]
I’m impartial!

**Comment by RichardLitt** [comment]
Let's go with GPL, then!
